"""
Page renderer target module.

Next refactor phase:
turn each route block from legacy/runtime.py into these functions.

def render_base(): ...
def render_missions(): ...
def render_evolution(): ...
def render_analytics(): ...
def render_oracle(): ...
def render_engine(): ...
def render_quests(): ...
def render_data(): ...
"""
